load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "bucketer",
    srcs = ["bucketer.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy/server/util/bucketer",
    visibility = ["//visibility:public"],
)
